module.exports={
    dev_host:"localhost",
    dev_port:8090,
    favicon:'./src/images/favicon.ico',
    commonname:"common",
    entrys:[
        {
            title:"主页",
            name:"index",
            entry:"./src/com/main.ts",
            template:'./src/htmls/index.html',
            filename:"./index.html"
        }
    ]
};