module.exports={
    dev_host:"192.168.40.227",
    dev_port:8090,
    favicon:'./src/images/favicon.ico',
    commonname:"common",
    entrys:[
        {
            title:"主页",
            name:"index",
            entry:"./src/com/main.ts",
            template:'./src/htmls/index.html',
            filename:"./index.html"
        },
        {
            title:"圆形碰撞",
            name:"circle-polygon",
            entry:"./src/com/circlePolygon/CircleCollide.ts",
            template:'./src/htmls/circle-polygon.html',
            filename:"./circle-polygon.html"
        }
    ]
};